### ISSUE TITLE
ERROR 404: Not Found when I download the AlphaFold files

### ISSUE THREAD

**Issue by sirius777coder** [microsoft/foldingdiff#1]
Great Work. I meet some small questions, when I use your script to download the AlphaFold data, it tells me that ERROR 404: Not Found.  May be there is something wrong with the AlphaFold database path.

**Comment by wukevin** [comment]
We haven't fully set up the AlphaFold datasets! We are currently focused on the CATH dataset and may eventually extend to AlphaFold dataset (or others) in the future.

**Comment by sirius777coder** [comment]
Thanks for your quick reply. Does models with different pdb data have different performance?

**Comment by sirius777coder** [comment]
And when I download the CATH data , it said : md5sum: cath/cath-dataset-nonredundant-S40.pdb.tgz: no properly formatted MD5 checksum lines found. It is correct?

**Comment by wukevin** [comment]
We haven't done an extensive evaluation on different datasets to be able to say which dataset produces optimal results. I'd intuitively expect that the more data you give the model to learn from, the better the end results. 

And yes the error message is expected.
