### ISSUE TITLE
Missing CATH dataset

### ISSUE THREAD

**Issue by KatarinaYuan** [microsoft/foldingdiff#14]
Hi,
    I tried to run the data downloading script `download_cath.sh` as suggested in README, but the error below showed up, saying "cath-dataset-nonredundant-S40.pdb.tgz" file is missing. 
    
<img width="883" alt="Screen Shot 2023-02-04 at 2 40 45 PM" src="https://user-images.githubusercontent.com/43512683/216786599-80cf738b-401a-4e68-8c17-64fe173fbc2a.png">

And I checked the remote file directory `/cath/releases/latest-release/non-redundant-data-sets` via FTP. There seems to be no files there. Wondering if you could help to fix it. Thanks a lot:)

**Comment by KatarinaYuan** [comment]
If the dataset is just the same as the one on CATH official website, could you specify which version of CATH you have used, for a fair comparison?

**Comment by wukevin** [comment]
It looks like the original URL is down; please use the following for now: https://www.dropbox.com/s/ka5m5lx58477qu6/cath-dataset-nonredundant-S40.pdb.tgz?dl=0
